#!/usr/bin/env bash
set -euo pipefail

STAMP=/etc/spiralos/wizard-done
OUT=/etc/nixos/spiralos-profiles.nix

force=false
if [ "${1:-}" = "--force" ]; then
  force=true
fi

if [ -e "$STAMP" ] && [ "$force" = false ]; then
  exit 0
fi

whiptail --title "spiralos setup" --msgbox \
  "welcome to spiralos\n\nthis wizard sets up your system based on your hardware and how you plan to use it, and writes ${OUT}\n\nre-run it anytime with spiralos-wizard --force" \
  14 70

# hardware detection

gpu_vendor="unknown"
if command -v lspci >/dev/null 2>&1; then
  vga=$(lspci -mm 2>/dev/null | grep -i 'VGA\|3D controller' || true)
  if echo "$vga" | grep -qi nvidia; then
    gpu_vendor="nvidia"
  elif echo "$vga" | grep -qi amd; then
    gpu_vendor="amd"
  elif echo "$vga" | grep -qi intel; then
    gpu_vendor="intel"
  fi
fi

is_laptop="false"
if compgen -G "/sys/class/power_supply/BAT*" > /dev/null 2>&1; then
  is_laptop="true"
fi

whiptail --title "detected hardware" --msgbox \
  "gpu vendor, ${gpu_vendor}\nlaptop (battery detected), ${is_laptop}\n\nthese set sensible defaults, you can override anything by hand-editing ${OUT} later" \
  12 70

# use-case presets

preset=$(whiptail --title "what will you mainly use this for" --menu \
  "pick a starting preset, you can fine-tune profiles on the next screen" 20 70 7 \
  workstation "general engineering workstation (rust, python, web)" \
  data-science "data science / ml (python, ml)" \
  maker "maker, electronics, embedded, cad/3d printing" \
  embedded "embedded / firmware development" \
  minimal "minimal, no profiles, just the spiralos base" \
  custom "choose profiles manually" \
  3>&1 1>&2 2>&3) || exit 1

case "$preset" in
  workstation) default_profiles="rust python web" ;;
  data-science) default_profiles="python ml" ;;
  maker) default_profiles="electronics embedded cad" ;;
  embedded) default_profiles="embedded" ;;
  minimal) default_profiles="" ;;
  custom) default_profiles="" ;;
esac

checklist_args=()
for p in rust python web ml embedded electronics cad; do
  state="OFF"
  for d in $default_profiles; do
    [ "$p" = "$d" ] && state="ON"
  done
  checklist_args+=("$p" "$p profile" "$state")
done

selected=$(whiptail --title "enable profiles" --checklist \
  "space to toggle, enter to confirm" 18 70 7 \
  "${checklist_args[@]}" \
  3>&1 1>&2 2>&3) || exit 1

# write config

mkdir -p /etc/nixos /etc/spiralos

# make sure configuration.nix imports our generated file
# touch a stub first, so it never points at a missing file
CONF=/etc/nixos/configuration.nix
touch "$OUT"
# best-effort, only matches a single "imports = [" line, a hand-edited
# configuration.nix with different formatting won't match - checked below
# so that case gets a manual-step prompt instead of silently doing nothing
if [ -f "$CONF" ] && ! grep -q 'spiralos-profiles.nix' "$CONF"; then
  sed -i '0,/imports = \[/s//imports = [\n    .\/spiralos-profiles.nix/' "$CONF"
  if ! grep -q 'spiralos-profiles.nix' "$CONF"; then
    whiptail --title "manual step needed" --msgbox \
      "couldn't find an \"imports = [ ... ]\" line to edit automatically in ${CONF}\n\nadd this line yourself, inside its imports list\n\n    ./spiralos-profiles.nix\n\nyour selected profiles were written to ${OUT} but won't take effect until it's imported" \
      14 70
  fi
fi

{
  echo "# generated by spiralos-wizard, safe to hand-edit afterwards"
  echo "# re-running the wizard overwrites this file unless --force is skipped"
  echo "{ ... }:"
  echo "{"
  # same loop as installer.sh's version of this, just inlined differently
  # since this one writes straight to $OUT instead of a temp file
  for p in $selected; do
    p="${p//\"/}"
    echo "  spiralos.profiles.${p}.enable = true;"
  done

  # wires the first normal login account into dialout/plugdev, for
  # serial/usb access, harmless if no maker profile is enabled
  primary_user=$(awk -F: '$3 >= 1000 && $3 < 60000 { print $1; exit }' /etc/passwd)
  if [ -n "$primary_user" ]; then
    echo "  spiralos.maker.user = \"${primary_user}\";"
  fi

  case "$gpu_vendor" in
    nvidia)
      echo "  hardware.graphics.enable = true;"
      echo "  services.xserver.videoDrivers = [ \"nvidia\" ];"
      ;;
    amd|intel)
      echo "  hardware.graphics.enable = true;"
      ;;
  esac

  if [ "$is_laptop" = "true" ]; then
    echo "  services.tlp.enable = true;"
  fi

  echo "}"
} > "$OUT"

mkdir -p /etc/spiralos
date > "$STAMP"

whiptail --title "done" --msgbox \
  "wrote ${OUT}\n\nrun 'sudo nixos-rebuild switch' to apply, or do it now" \
  10 70

if whiptail --title "apply now" --yesno "run nixos-rebuild switch now" 8 60; then
  if ! nixos-rebuild switch; then
    whiptail --title "rebuild failed" --msgbox \
      "nixos-rebuild switch failed, your system wasn't changed, run it again by hand to see the full error, or fix ${OUT} and retry" \
      10 70
  fi
fi
