#!/usr/bin/env bash
set -euo pipefail

STAMP=/etc/spiralos/wizard-done
OUT=/etc/nixos/spiralos-profiles.nix

force=false
if [ "${1:-}" = "--force" ]; then
  force=true
fi

if [ -e "$STAMP" ] && [ "$force" = false ]; then
  exit 0
fi

whiptail --title "SpiralOS Setup" --msgbox \
  "Welcome to SpiralOS.\n\nThis wizard configures your system based on your hardware and how you plan to use it. It writes ${OUT}, which your configuration.nix already imports.\n\nYou can re-run this anytime with: spiralos-wizard --force" \
  14 70

# --- hardware detection -----------------------------------------------

gpu_vendor="unknown"
if command -v lspci >/dev/null 2>&1; then
  vga=$(lspci -mm 2>/dev/null | grep -i 'VGA\|3D controller' || true)
  if echo "$vga" | grep -qi nvidia; then
    gpu_vendor="nvidia"
  elif echo "$vga" | grep -qi amd; then
    gpu_vendor="amd"
  elif echo "$vga" | grep -qi intel; then
    gpu_vendor="intel"
  fi
fi

is_laptop="false"
if compgen -G "/sys/class/power_supply/BAT*" > /dev/null 2>&1; then
  is_laptop="true"
fi

whiptail --title "Detected hardware" --msgbox \
  "GPU vendor: ${gpu_vendor}\nLaptop (battery detected): ${is_laptop}\n\nThese will be used to set sensible defaults; you can override anything by hand-editing ${OUT} later." \
  12 70

# --- use-case presets ----------------------------------------------------

preset=$(whiptail --title "What will you mainly use this for?" --menu \
  "Pick a starting preset (you can fine-tune profiles on the next screen)" 20 70 7 \
  workstation "General engineering workstation (rust, python, web)" \
  data-science "Data science / ML (python, ml)" \
  maker "Maker: electronics, embedded, CAD/3D printing" \
  embedded "Embedded / firmware development" \
  minimal "Minimal — no profiles, just the SpiralOS base" \
  custom "Choose profiles manually" \
  3>&1 1>&2 2>&3) || exit 1

case "$preset" in
  workstation) default_profiles="rust python web" ;;
  data-science) default_profiles="python ml" ;;
  maker) default_profiles="electronics embedded cad" ;;
  embedded) default_profiles="embedded" ;;
  minimal) default_profiles="" ;;
  custom) default_profiles="" ;;
esac

checklist_args=()
for p in rust python web ml embedded electronics cad; do
  state="OFF"
  for d in $default_profiles; do
    [ "$p" = "$d" ] && state="ON"
  done
  checklist_args+=("$p" "$p profile" "$state")
done

selected=$(whiptail --title "Enable profiles" --checklist \
  "Space to toggle, Enter to confirm" 18 70 7 \
  "${checklist_args[@]}" \
  3>&1 1>&2 2>&3) || exit 1

# --- write config ----------------------------------------------------------

mkdir -p /etc/nixos /etc/spiralos

# make sure configuration.nix actually imports our generated file. touch a
# stub first so we never leave configuration.nix pointing at a missing file.
CONF=/etc/nixos/configuration.nix
touch "$OUT"
if [ -f "$CONF" ] && ! grep -q 'spiralos-profiles.nix' "$CONF"; then
  sed -i '0,/imports = \[/s//imports = [\n    .\/spiralos-profiles.nix/' "$CONF"
fi

{
  echo "# Generated by spiralos-wizard. Safe to hand-edit afterwards;"
  echo "# re-running the wizard will overwrite this file unless --force is skipped."
  echo "{ ... }:"
  echo "{"
  for p in $selected; do
    p="${p//\"/}"
    echo "  spiralos.profiles.${p}.enable = true;"
  done

  # if a maker-oriented profile is selected, wire the primary user into the
  # dialout/plugdev groups for serial/usb device access. detect the first
  # normal login account (uid 1000-59999). harmless when maker is disabled.
  primary_user=$(awk -F: '$3 >= 1000 && $3 < 60000 { print $1; exit }' /etc/passwd)
  if [ -n "$primary_user" ]; then
    echo "  spiralos.maker.user = \"${primary_user}\";"
  fi

  case "$gpu_vendor" in
    nvidia)
      echo "  hardware.graphics.enable = true;"
      echo "  services.xserver.videoDrivers = [ \"nvidia\" ];"
      ;;
    amd|intel)
      echo "  hardware.graphics.enable = true;"
      ;;
  esac

  if [ "$is_laptop" = "true" ]; then
    echo "  services.tlp.enable = true;"
  fi

  echo "}"
} > "$OUT"

mkdir -p /etc/spiralos
date > "$STAMP"

whiptail --title "Done" --msgbox \
  "Wrote ${OUT}.\n\nRun 'sudo nixos-rebuild switch' to apply, or do it now." \
  10 70

if whiptail --title "Apply now?" --yesno "Run nixos-rebuild switch now?" 8 60; then
  nixos-rebuild switch || true
fi
